// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package pgstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLegalEntity = `-- name: CreateLegalEntity :one
INSERT INTO legal_entities (
  trade_name,
  age,
  corporate_email,
  revenue
) VALUES (
  $1,
  $2,
  $3,
  $4
)
RETURNING id, trade_name, age, revenue, corporate_email
`

type CreateLegalEntityParams struct {
	TradeName      string         `json:"trade_name"`
	Age            int32          `json:"age"`
	CorporateEmail string         `json:"corporate_email"`
	Revenue        pgtype.Numeric `json:"revenue"`
}

func (q *Queries) CreateLegalEntity(ctx context.Context, arg CreateLegalEntityParams) (LegalEntity, error) {
	row := q.db.QueryRow(ctx, createLegalEntity,
		arg.TradeName,
		arg.Age,
		arg.CorporateEmail,
		arg.Revenue,
	)
	var i LegalEntity
	err := row.Scan(
		&i.ID,
		&i.TradeName,
		&i.Age,
		&i.Revenue,
		&i.CorporateEmail,
	)
	return i, err
}

const createNaturalPerson = `-- name: CreateNaturalPerson :one
INSERT INTO natural_persons (
  full_name,
  age,
  email,
  monthly_income
) VALUES (
  $1,
  $2,
  $3,
  $4
)
RETURNING id, full_name, age, monthly_income, email
`

type CreateNaturalPersonParams struct {
	FullName      string         `json:"full_name"`
	Age           int32          `json:"age"`
	Email         string         `json:"email"`
	MonthlyIncome pgtype.Numeric `json:"monthly_income"`
}

func (q *Queries) CreateNaturalPerson(ctx context.Context, arg CreateNaturalPersonParams) (NaturalPerson, error) {
	row := q.db.QueryRow(ctx, createNaturalPerson,
		arg.FullName,
		arg.Age,
		arg.Email,
		arg.MonthlyIncome,
	)
	var i NaturalPerson
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Age,
		&i.MonthlyIncome,
		&i.Email,
	)
	return i, err
}
