// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pgstore

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID              uuid.UUID          `json:"id"`
	NaturalPersonID pgtype.UUID        `json:"natural_person_id"`
	LegalEntityID   pgtype.UUID        `json:"legal_entity_id"`
	CategoryID      int32              `json:"category_id"`
	MobilePhone     pgtype.Text        `json:"mobile_phone"`
	Balance         pgtype.Numeric     `json:"balance"`
	CreatedAt       time.Time          `json:"created_at"`
	ClosedAt        pgtype.Timestamptz `json:"closed_at"`
}

type Category struct {
	ID           int32  `json:"id"`
	CategoryName string `json:"category_name"`
}

type LegalEntity struct {
	ID             uuid.UUID      `json:"id"`
	TradeName      string         `json:"trade_name"`
	Age            int32          `json:"age"`
	Revenue        pgtype.Numeric `json:"revenue"`
	CorporateEmail string         `json:"corporate_email"`
}

type NaturalPerson struct {
	ID            uuid.UUID      `json:"id"`
	FullName      string         `json:"full_name"`
	Age           int32          `json:"age"`
	MonthlyIncome pgtype.Numeric `json:"monthly_income"`
	Email         string         `json:"email"`
}
