// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: natural_persons.sql

package pgstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNaturalPerson = `-- name: CreateNaturalPerson :one
INSERT INTO natural_persons (
  full_name,
  age,
  email,
  monthly_income
) VALUES (
  $1,
  $2,
  $3,
  $4
) RETURNING id, full_name, age, monthly_income, email
`

type CreateNaturalPersonParams struct {
	FullName      string         `json:"full_name"`
	Age           int32          `json:"age"`
	Email         string         `json:"email"`
	MonthlyIncome pgtype.Numeric `json:"monthly_income"`
}

func (q *Queries) CreateNaturalPerson(ctx context.Context, arg CreateNaturalPersonParams) (NaturalPerson, error) {
	row := q.db.QueryRow(ctx, createNaturalPerson,
		arg.FullName,
		arg.Age,
		arg.Email,
		arg.MonthlyIncome,
	)
	var i NaturalPerson
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Age,
		&i.MonthlyIncome,
		&i.Email,
	)
	return i, err
}
